name: Update Release Draft

on:
  push:
    branches: [ main ]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    steps:
    # Drafts your next Release notes as Pull Requests are merged into "main"
    - name: Draft release notes
      id: draft
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
